context("Test context for discovered model function")
source("config.R")

#the expected model data were generated by the Appian Process Mining frontend

test_that("Direct follower results", {
  directFollowers_is <- discoveredModel(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = '[]'
                              )$directFollowerStatistics$directFollowers %>% select_if(~sum(!is.na(.)) > 0)

  directFollowers_exp <-  read_json(path = paste0(filePath,'response_1.json'))$directFollowerStatistics$directFollowers %>%
                                  map_df(flatten) %>% unnest() %>% select_if(~sum(!is.na(.)) > 0)

  testthat::expect_identical(directFollowers_exp, directFollowers_is)

})

test_that("Activity performance results", {
  activityPerformanceStatistics_is <- discoveredModel(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = '[]'
                              )$activityPerformanceStatistics

  activityPerformanceStatistics_exp <-  read_json(path = paste0(filePath,'response_1.json'))$activityPerformanceStatistics

  testthat::expect_identical(activityPerformanceStatistics_exp, activityPerformanceStatistics_is)

})

test_that("Discovered model results", {
  discoveredModel_is <- discoveredModel(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = '[]', renderDiscoveredModel = TRUE
                              )$discoveredModel

  discoveredModel_exp <-  read_json(path = paste0(filePath,'response_model.json'))$discoveredModel

  testthat::expect_identical(discoveredModel_exp, discoveredModel_is)

})

test_that("conformanceResult returns the expected values", {
  conres_is <- conformanceResult(logId = selectedLogId,
                              lanaToken = lanaToken,
                              lanaUrl = lanaUrl,
                              traceFilterSequence = '[]'
  )
  
  conres_exp <- list("activity" = c("Incident logging", 
                      "Resolution and recovery", 
                      "Incident classification", 
                      "Incident closure", 
                      "Initial diagnosis", 
                      "Functional escalation",     
                      "Investigation and diagnosis"),
                     "conform" = c(2000,
                                   1635,
                                   2000,
                                   2000,
                                   2000,
                                   759,
                                   759),
                     "insert" = c(0,
                                  0,
                                  0,
                                  0,
                                  337,
                                  92,
                                  92),
                     "skip" = c(0,
                                134,
                                0,
                                0,
                                0,
                                0,
                                0)) %>%
                      as.data.frame
  
  testthat::expect_equal(conres_is, conres_exp)
  
})

test_that("logStatistics return the expected values", {
  logstat_is <- logStatistics(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = '[]'
                              )
  
  logstat_exp <- list(
    "avgTraceDuration" = 42516060,
    "maxTimeStamp" = 1452137504000,
    "maxTraceDuration" = 224640000,
    "medianTraceDuration" = 21810000,
    "minTimeStamp" = 1451898944000,
    "minTraceDuration" = 5760000,
    "numEvents" = 11674,
    "numTraces" = 2000,
    "numVariants" = 8,
    "standardDeviationDuration" = 39786851.49207265,
    "varianceDuration" = 1582993551652243.5
  ) %>%
    t() %>%
    data.frame()
  
  testthat::expect_equal(logstat_is, logstat_exp)

})
