context("Test context for discovered model function")
source("config.R")

# the expected model data were generated by the Appian Process Mining frontend

test_that("Direct follower results", {
  directFollowers_is <- directFollowers(
    logId = selectedLogId,
    lanaToken = lanaToken,
    lanaUrl = lanaUrl,
    traceFilterSequence = list()) %>%
    select(maxDuration, pre, succ) %>%
    slice(1:4)

  maxDuration <- c(240000, 7380000, 1320000, 240000)
  pre <- c("Resolution and recovery", "Initial diagnosis", "Incident classification", "Incident logging")
  succ <- c("Incident closure", "Incident closure", "Initial diagnosis", "Incident classification")

  directFollowers_exp <- data.frame(maxDuration, pre, succ)

  testthat::expect_equal(directFollowers_exp, directFollowers_is)
})

test_that("Activity performance results", {
  activityPerformanceStatistics_is <- activityPerformance(
    logId = selectedLogId,
    lanaToken = lanaToken,
    lanaUrl = lanaUrl,
    traceFilterSequence = list()) %>%
    select(activity, frequency, totalDuration) %>%
    slice(1:4)

  activity <- c("Functional escalation", "Incident classification", "Incident closure", "Incident logging")
  frequency <- c(851, 2000, 2000, 2000)
  totalDuration <- c(254640000, 497580000, 1582380000, 1079040000)

  activityPerformanceStatistics_exp <- data.frame(activity, frequency, totalDuration)

  testthat::expect_equal(activityPerformanceStatistics_exp, activityPerformanceStatistics_is)
})

test_that("Discovered model results", {
  discoveredModel_is <- discoveredModel(
    logId = selectedLogId,
    lanaToken = lanaToken,
    lanaUrl = lanaUrl,
    traceFilterSequence = "[]", renderDiscoveredModel = TRUE, runConformance = TRUE
  )$discoveredModel$flowIds

  discoveredModel_exp <- list(
    `Functional escalation->Investigation and diagnosis` = "df_3-4",
    `Incident classification->Initial diagnosis` = "df_1-2",
    `Incident closure->__PROCESS_END__` = "df_6--3",
    `Incident logging->Incident classification` = "df_0-1",
    `Initial diagnosis->Functional escalation` = "df_2-3",
    `Initial diagnosis->Incident closure` = "df_2-6",
    `Initial diagnosis->Resolution and recovery` = "df_2-5",
    `Investigation and diagnosis->Incident closure` = "df_4-6",
    `Investigation and diagnosis->Initial diagnosis` = "df_4-2",
    `Investigation and diagnosis->Resolution and recovery` = "df_4-5",
    `Resolution and recovery->Incident closure` = "df_5-6",
    `__PROCESS_START__->Incident logging` = "df_-2-0"
  )

  testthat::expect_equal(discoveredModel_exp, discoveredModel_is)
})

test_that("logStatistics return the expected values", {
  logstat_is <- logStatistics(
    logId = selectedLogId,
    lanaToken = lanaToken,
    lanaUrl = lanaUrl,
    traceFilterSequence = "[]"
  )

  colnames <- c(
    "avgTraceDuration",
    "maxTimeStamp",
    "maxTraceDuration",
    "medianTraceDuration",
    "minTimeStamp",
    "minTraceDuration",
    "numEvents",
    "numTraces",
    "numVariants",
    "standardDeviationDuration",
    "varianceDuration"
  )

  values <- c(
    42516060,
    1452137504000,
    224640000,
    21810000,
    1451898944000,
    5760000,
    11674,
    2000,
    8,
    39786851.4920727,
    1582993551652245
  )

  logstat_exp <- as.data.frame(t(values))
  names(logstat_exp) <- colnames

  testthat::expect_equal(logstat_is, logstat_exp)
})
