context("Test context for discovered model function")
#source("config.R")

filePath <-paste0(getwd(), '/', 'test_responses/')
#the expected model data were generated by the Appian Process Mining frontend

test_that("Direct follower results", {
  directFollowers_is <- directFollowers(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = list())


  #directFollowers_exp <-  read_json(path = paste0(filePath,'response_1.json'))$directFollowerStatistics$directFollowers %>%
  #                                map_df(flatten) %>% unnest() %>% select_if(~sum(!is.na(.)) > 0)

  directFollowers_exp <- lanar::discoveredModel(lanaUrl, lanaToken, selectedLogId,
                                       traceFilterSequence = '[]',
                                       runConformance ="true" )$directFollowerStatistics$directFollowers %>%
                          select_if(~sum(!is.na(.)) > 0)

  testthat::expect_equal(directFollowers_exp, directFollowers_is)

})

test_that("Activity performance results", {
  activityPerformanceStatistics_is <- activityPerformance(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = list()
                              )

  activityPerformanceStatistics_exp <- lanar::discoveredModel(lanaUrl, lanaToken, selectedLogId,
                                       traceFilterSequence = '[]',
                                       runConformance ="true" )$activityPerformanceStatistics %>%
                                       do.call(rbind, .) %>%
                                        as.data.frame %>%
                                        tibble::rownames_to_column("Activity") %>%
                                        select_if(~!all(is.null(.)))



  testthat::expect_equal(activityPerformanceStatistics_exp, activityPerformanceStatistics_is)

})

test_that("Discovered model results", {
  discoveredModel_is <- discoveredModel(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = '[]', renderDiscoveredModel = TRUE, runConformance = TRUE
                              )$discoveredModel

  discoveredModel_exp <-  lanar::discoveredModel(lanaUrl, lanaToken, selectedLogId,
                                       traceFilterSequence = '[]',
                                       renderDiscoveredModel ="true" , runConformance = "true")$discoveredModel

  testthat::expect_equal(discoveredModel_exp, discoveredModel_is)

})

test_that("conformanceResult returns the expected values", {
  conres_is <- conformanceResult(logId = selectedLogId,
                              lanaToken = lanaToken,
                              lanaUrl = lanaUrl,
                              traceFilterSequence = '[]'
  )
  
  conres_exp <- lanar::discoveredModel(lanaUrl, lanaToken, selectedLogId,
                                       traceFilterSequence = '[]',
                                       runConformance ="true" )$conformanceResult$activityDeviationCounts
  
  testthat::expect_equal(conres_is, conres_exp)
  
})

test_that("logStatistics return the expected values", {
  logstat_is <- logStatistics(logId = selectedLogId,
                               lanaToken = lanaToken,
                               lanaUrl = lanaUrl,
                               traceFilterSequence = '[]'
                              )
  
  logstat_exp <- lanar::discoveredModel(lanaUrl, lanaToken, selectedLogId,
                                       traceFilterSequence = '[]',
                                       runConformance ="true" )$logStatistics %>%
                                        within(rm(
                                        "numericAttributeRanges", "attributeCounts",
                                        "conformanceStatistics")) %>%
                                        t() %>%
                                        as.data.frame
  
  testthat::expect_equal(logstat_is, logstat_exp)

})
